name: Nuget
on: workflow_dispatch
  
jobs:

  build_nuget:

    runs-on: windows-latest 
    
    permissions:
      packages: write
      contents: read
      
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x
        
    - name: Create Package
      run: dotnet pack
      working-directory: PowerCollections
      

      
    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with: 
        xml-file: "PowerCollections.csproj"
        xpath: '//version'
    - name: Create Release 
      uses: ncipollo/release-action@v1.12.0
      with: 
        artifacts: 'PowerCollections\PowerCollections\bin\Debug\*${{ steps.getxml.outputs.info }}.nupkg'
        tag: ${{ steps.getxml.outputs.info }}
