name: Task03

on:
  push:
    branches: 
      - "main"
      - "Task03"

jobs:

  build:

    runs-on: windows-latest 

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: PowerCollections
    - name: Build
      run: dotnet build --no-restore
      working-directory: PowerCollections
    - name: Execute unit tests
      run: dotnet test --no-build
      working-directory: PowerCollections
